# Generated by Django 4.2.4 on 2023-08-29 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslateText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_language', models.CharField(blank=True, max_length=100, null=True)),
                ('original_text', models.TextField()),
                ('to_language', models.CharField(blank=True, max_length=100, null=True)),
                ('translated_text', models.TextField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translate Text',
                'verbose_name_plural': 'Translate Texts',
                'db_table': 'translate_text',
            },
        ),
    ]
